### ISSUE TITLE
[BUG] Missing Credits

### ISSUE THREAD

**Issue by IdealistCat** [DragginGroup/Pupet#4]
**Describe the bug**
The Credits are missing

**To Reproduce**
1. Start Game
2. Go to Credits Menu

**Expected behavior**
A Credits Page that you can scroll through

**Screenshots**
![Screenshot_20240902_191135_Chrome](https://github.com/user-attachments/assets/5826e378-2751-4c47-a926-1e42e70b35db)

**Device (please complete the following information):**
 - Device: Phone
 - OS: Samsung Galaxy
 - Browser: Chrome
 
**Game info**
- Version: pre-1.10

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
