### ISSUE TITLE
[BUG] Incorrect Changelog

### ISSUE THREAD

**Issue by IdealistCat** [DragginGroup/Pupet#5]
**Describe the bug**

**To Reproduce**
1. Start Game
2. Go to Changelog Page

**Expected behavior**
Changelog for pre-1.10

**Screenshots**
![Screenshot_20240902_191151_Chrome](https://github.com/user-attachments/assets/c56a5e95-4152-46bd-a5d8-f6eaec62141a)

**Device (please complete the following information):**
 - Device: Mobile
 - OS: Samsung Galaxy
 - Browser: Chrome
 
**Game info**
- Version: pre-1.10

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
