### ISSUE TITLE
[BUG]Status text glitched

### ISSUE THREAD

**Issue by iampauleps** [DragginGroup/Pupet#7]
When i pressed status the text was all jumbled up
![Screenshot_62](https://github.com/user-attachments/assets/33cc6176-8d3d-43cd-99f9-2a0c60df9c47)

**Comment by IdealistCat** [comment]
This is because of the alignment and the new method of text vertical position changing.

**Comment by IdealistCat** [comment]
Will be fixed! Do not worry.🙏
